allowBuilds:
  '@sentry/cli': set this to true or false
  core-js: set this to true or false
  core-js-pure: set this to true or false
  esbuild: set this to true or false
  unrs-resolver: set this to true or false
onlyBuiltDependencies:
  - '@sentry/cli'
  - core-js
  - core-js-pure
  - esbuild
  - unrs-resolver
