allowBuilds:
  '@sentry/cli': true
  core-js: true
  core-js-pure: true
  esbuild: true
  unrs-resolver: true
onlyBuiltDependencies:
  - '@sentry/cli'
  - core-js
  - core-js-pure
  - esbuild
  - unrs-resolver
